#用户凭证，必填
user_token: 'eyxxxxx'

data:
  #
  action: 1

  #
  category: 1

  #
  speed_type: 1

  meta:
    #负面提示词
    negative_prompt: "verybadimagenegative_v1.3, ng_deepnegative_v1_75t, (ugly face:0.8),cross-eyed,sketches, (worst quality:2), (low quality:2), (normal quality:2), lowres, normal quality, ((monochrome)), ((grayscale)), skin spots,            acnes, skin blemishes, bad anatomy, DeepNegative, facing away, tilted head, {Multiple people}, lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worstquality, low quality, normal quality, jpegartifacts, signature, watermark, username, blurry, bad feet, cropped, poorly drawn hands, poorly drawn face, mutation, deformed, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, extra fingers, fewer digits, extra limbs, extra arms,extra legs, malformed limbs, fused fingers, too many fingers, long neck, cross-eyed,mutated hands, polar lowres, bad body, bad proportions, gross proportions, text, error, missing fingers, missing arms, missing legs, extra digit, extra arms, extra leg, extra foot, ((repeating hair))"

    #采样方法
    sampler_name: "DPM++ 2M Karras"

    #图片宽度，-普通 范围 {288-512}；-高清 范围 {432-768} -超清 范围 {576-1024}
    width: 512

    #图片长度，-普通 范围 {288-512}；-高清 范围 {432-768} -超清 范围 {576-1024}
    height: 768

    #采样步数，范围 {10-40}
    steps: 20

    #文本强度，范围 {3-15}
    cfg_scale: 7

    #图像的色彩表现，可选择: automatic,None,vae-ft-mse-840000-ema-pruned,vae-ft-ema-560000-ema-pruned,kl-f8-trinart_characters,kl-f8-anime2,ClearVAE
    vae: "vae-ft-mse-840000-ema-pruned"

    #减少提示词色彩污染，范围 {1-5}
    clip_skip: 2

    #执行步数，不建议修改
    hr_second_pass_steps: 20

    #不建议修改
    restore_faces: false

    #不建议修改
    lcm_mode: 0

    #不建议修改
    n_iter: 1